# PROGRAM 13
##### Aim :  Write a numpy program to access array by column
##### Date :19/08/2022 
##### By   :Anu C Scharia

In [10]:
import numpy as np
x=np.arange(9).reshape(3,3)
print("Original array :\n",x)
print("First column :",x[::,0])
print("Second column :",x[::,1])
print("Thrid column :",x[::,2])

Original array :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
First column : [0 3 6]
Second column : [1 4 7]
Thrid column : [2 5 8]
