# PROGRAM 17
##### Aim :  Write a Pandas program to create and display a one-dimensional array like object containing an array of data 
##### Date :24/08/2022 
##### By   :Anu C Scharia

In [13]:
import numpy as np
m=np.array([[2,3,1],[1,2,3],[5,1,2]])
print(m)
print("Transpose :",np.transpose(m))
print("Determinant :",np.linalg.det(m))
print("Inverse :",np.linalg.inv(m))

[[2 3 1]
 [1 2 3]
 [5 1 2]]
Transpose : [[2 1 5]
 [3 2 1]
 [1 3 2]]
Determinant : 32.0
Inverse : [[ 0.03125 -0.15625  0.21875]
 [ 0.40625 -0.03125 -0.15625]
 [-0.28125  0.40625  0.03125]]
