# PROGRAM 8
##### Aim : checkboard pattern
[[1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 0 0 1 1]
 [0 0 1 1 1 1 0 0]
 [1 1 0 0 0 0 1 1]
 [0 0 1 1 1 1 0 0]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]]
##### Date :17/08/2022 
##### By   :Anu C Scharia

In [2]:
arr=np.zeros((8,8),dtype=int)
arr[0::2,:2:]=1
arr[1::2,2:4:]=1

arr[0:1:1,4:6:]=1
arr[1:3:,6::]=1

arr[3:4:1,4:6:]=1
arr[4:5:,6::]=1

arr[5:7:1,4:6:]=1
arr[7::1,6::]=1
print(arr)

[[1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 0 0 1 1]
 [0 0 1 1 1 1 0 0]
 [1 1 0 0 0 0 1 1]
 [0 0 1 1 1 1 0 0]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]]
