# PROGRAM 6
##### Aim : Write a numpy program to create a 8 x 8 matrix and fill it with a checkerboard pattern
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

##### Date :17/08/2022 
##### By   :Anu C Scharia

In [3]:
arr=np.zeros((8,8),dtype=np.int64)
arr[::2,1::2]=1
arr[1::2,::2]=1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
