# PROGRAM 14
##### Aim :  Write a numpy program to compute
   a)  multiplication of two given matrices.
   b)  addition of two matrices
##### Date :19/08/2022 
##### By   :Anu C Scharia

In [11]:
import numpy as np
m1=np.arange(9).reshape(3,3)
m2=np.array([[2,3,4],[1,2,3],[6,1,2]])
print("First matrix :\n",m1)
print("Secon matrix :\n",m2)
r1=np.matmul(m1,m2)
r2=m1+m2
print("Matrix Multiplication :\n",r1)
print("Sum of matrix :\n",r2)

First matrix :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Secon matrix :
 [[2 3 4]
 [1 2 3]
 [6 1 2]]
Matrix Multiplication :
 [[13  4  7]
 [40 22 34]
 [67 40 61]]
Sum of matrix :
 [[ 2  4  6]
 [ 4  6  8]
 [12  8 10]]
